#!/bin/sh

ETCVOL="dante"

DOCKER_CMD="docker run --rm -i -v ${ETCVOL}:/etc ubuntu:xenial"

USER_NAME=${1}
PASSWORD=${2}

if [ -z "$USER_NAME" ]; then
    echo "Usage:"
    echo "$0 USER [PASSWORD]"
    exit 1
fi

if [ -z "$PASSWORD" ]; then
    PASSWORD=`apg -M NCL -m 16 -x 16 -n 1`
    echo "$USER_NAME $PASSWORD"
fi

echo "${USER_NAME}:${PASSWORD}" | ${DOCKER_CMD}  chpasswd
